name: naumen_smp_jsapi
description: Простая библиотека для работы с API Naumen SMP для Dartlang.
version: '1.0.5'
homepage: 'https://github.com/mdemyanov/naumen-smp-jsapi'
author: 'mdemyanov <mdemyanov@naumen.ru>'

environment:
  sdk: '>=1.21.0 < 3.0.0'

dependencies:
  http: "^0.11.3+17"

dev_dependencies:
  test: "^1.0.0"